"""
Django settings for OAuth2DjangoSampleApp project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4-q9i$$hhq-%ur9t=kpnpt5=eb=2j971t+$=buq^y0ngovj25b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Django will always save session information to the database for every request
SESSION_SAVE_EVERY_REQUEST = True

ALLOWED_HOSTS = [
    'localhost','127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'sampleAppOAuth2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'requests',
    'SampleInvoiceCRUDUsingDict'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OAuth2DjangoSampleApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(os.path.realpath(__file__)), "../sampleAppOAuth2/templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OAuth2DjangoSampleApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]

# OAuth specific variables
DISCOVERY_DOCUMENT = 'https://developer.api.intuit.com/.well-known/openid_sandbox_configuration/'
CLIENT_ID = 'ABFYBN0R1fNfq90S9Z24N0QIvMhmn5JNNO8wKrmi28dC3HhRie'
CLIENT_SECRET = 'A6ny4rkmSWNYe50wDrZdYOqontx0c2BUI1f2P9j1'
REDIRECT_URI = 'https://developer.intuit.com/v2/OAuth2Playground/RedirectUrl'
ACCOUNTING_SCOPE = 'com.intuit.quickbooks.accounting'
OPENID_SCOPES = ['openid', 'profile', 'email', 'phone', 'address']
GET_APP_SCOPES = ['com.intuit.quickbooks.accounting', 'openid', 'profile', 'email', 'phone', 'address']
SANDBOX_QBO_BASEURL = 'https://sandbox-quickbooks.api.intuit.com'
SANDBOX_PROFILE_URL = 'https://sandbox-accounts.platform.intuit.com/v1/openid_connect/userinfo'
ID_TOKEN_ISSUER = 'https://oauth.platform.intuit.com/op/v1'
realm_id = "193514846598994"

oauth_flag = 2
access_token_oauth2 = "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..4BactPTdngukbyfuOMe6EA.y_WO_N1QOInR1S6mWv0lpwipDMWPSSMTKog9lxXksIOr_XKN1I6-iOHL6LB2YH73d55U-w52bKa6nfLw-eFNQMyRkbH4SFVjMZ2dO8zGtV0aSeRy58OCDmDDLJ55Uv8xfKifERGMhrFZ8YjChYKe59BOKEtYGezG_erxwFDMZoM-D8uliYDLGy8XbjZiTmthoJoE9I8D05UoEGrcFRax5bJb5a_znCDsW-iyJg0oU86hIR-IyJx_FXBvn79ovPNcmGQqU9oy-Wr2nWSH6n9bk8fF0sTgu1Okq6YPTmMcayCu0WBzVw_bwnr5Ip8Jf7ZNUCfBblgWDdLEpVeZxDWlF8YAXKVG21T4cd6zBBFM8zczqGwGeYxC9XZWbDZoklqokM3Qxm_zlNByexlevaBfK7igyiw4bCkQUNG5HtkMk5w_pMhKWWD0NhPZoa912mAkFkejYzgHwYLbmbTt7k_z0UXX8FYoH4GphNIZGZk-iCKokcDDffmHPUprDEAuiWAoZnY7bRfTi0ZzM13MEKI04yRP0HtjA1nXUpocj7gtzOHT-y4Z30KCJOY01D4Yo-tbiAsnk4zvtiXPyhUNWkzaxbiLamWOez7uYxYCXI-wUucgpPsJQtFFYE_cXY_QhcCvg3VQnqkqyQpxtS3zyrGCud6okFROMXEqIljlBn3I8kaCyU_xzHbN2RreKgp9HIOB65lX4xRVr8yVdQ8mCS8DYUIPXrxpvwsWQJg1-WXotfM.WSZwd0MJOrwbJMFlsM1bGQ"
base_url = 'https://sandbox-quickbooks.api.intuit.com'
